apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.image-pull-policy: Always
    kompose.service.healthcheck.readiness.http_get_path: /
    kompose.service.healthcheck.readiness.http_get_port: "3000"
    kompose.service.healthcheck.readiness.initial_delay_seconds: "10"
    kompose.service.healthcheck.readiness.period_seconds: "5"
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: photobin-frontend
  name: photobin-frontend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: photobin-frontend
